<a href="https://colab.research.google.com/github/ramakanth-rayanchi/CB-DL-01/blob/main/C10_Matrix_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

In [15]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [16]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [17]:
# Lets work on getting the sales for each year based on the price per product and quantity sold in each year

price_per_unit = np.array([1000, 400, 1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [18]:
# If we do simple multiplication
price_per_unit*units

# Numpy uses concept of broadcast if both arrays are not the same size

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [19]:
# https://numpy.org/doc/stable/user/basics.broadcasting.html

In [20]:
# To get sales for each year, use dot product
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

In [21]:
# Now Excercise

# https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbkUxTUJYSzJ3UTB6X2xkS2tITDM3R2hhaUE0QXxBQ3Jtc0tsTzM5T29oZXF1RFM5VUgtQmRINHZXaE1qemZ5eEMxN3F1NGhaVGNmWGphM1hNRHJ3UEJOZV9hZy1Nc0Z3VlpCdnJLSDBpSXZXNW5YYkU2LXVEMEJsZkI3ZldpOWk4QlNHWTIxbldERFVvQTdLZWFFSQ&q=https%3A%2F%2Fgithub.com%2Fcodebasics%2Fdeep-learning-keras-tf-tutorial%2Fblob%2Fmaster%2F4_matrix_math%2F4_matrix_math.md&v=Wibxjrxf5ko

Exercise: Matrix Math
Below is some indian companies revenues in US dollars. Using numpy can you convert this into Indian rupees? 1 USD = 75 INR


In [22]:
company_in_dollar = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
company_in_rupees = company_in_dollar*75
company_in_rupees

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

Divine flowers is a flower shop that sells different type of flowers. Below is the table showing how many flowers of each type they sold in different months. Also given are the prices of one flower each. Using this find out their total sales in every month.

In [27]:
prices_per_unit = np.array([[20],[30],[15]])
prices_per_unit.shape

(3, 1)

In [24]:
units_sold =np.array([[50,60,25],[10,13,5],[40,70,52]])
units_sold.shape

(3, 3)

In [28]:
np.dot(prices_per_unit, units_sold)

ValueError: ignored

In [30]:
# the above is wrong answer. Lets reshape the price_per_unit array
prices_per_unit_reshaped = np.reshape(prices_per_unit, (1,3))
prices_per_unit_reshaped


array([[20, 30, 15]])

In [31]:
# lets try the dot product again
np.dot(prices_per_unit_reshaped, units_sold)

array([[1900, 2640, 1430]])

https://www.mathopolis.com/questions/q.html?id=714&t=mif&qs=714_715_716_717_2394_2395_2397_2396_8473_8474_8475_8476&site=1&ref=2f616c67656272612f6d61747269782d6d756c7469706c79696e672e68746d6c&title=486f7720746f204d756c7469706c79204d61747269636573