<a href="https://colab.research.google.com/github/ramakanth-rayanchi/CB-DL-01/blob/main/C11_loss_or_cost_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.3,0.7,1,0,0.5])



### Implement Mean Absolute Error

In [2]:
# Without numpy functions
def mae(y_predicted, y_true):
  total_error = 0
  for yp, yt in zip(y_predicted, y_true):
    print(yp,yt)
    total_error = total_error + abs(yp-yt)
  print("total error=", total_error)
  mae = total_error/len(y_true)
  print("mae=",mae)
  return mae

In [3]:
mae(y_predicted, y_true)

1 0.3
1 0.7
0 1.0
0 0.0
1 0.5
total error= 2.5
mae= 0.5


0.5

Implement same thing using numpy in much easier way

In [4]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [5]:
np.sum(np.abs(y_predicted - y_true))

2.5

In [6]:
np.mean(np.abs(y_predicted - y_true))

0.5

In [7]:
def mae_np(y_predicted, y_true):
  return np.mean(np.abs(y_predicted - y_true))

In [8]:
mae_np(y_predicted, y_true)

0.5

### Implement Log Loss or Binary Cross Entropy

In [9]:
np.log([0])

<ipython-input-9-faee82fd9f21>:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [10]:
epsilon = 1e-15

In [11]:
np.log([epsilon])

array([-34.53877639])

In [12]:
y_predicted

array([1, 1, 0, 0, 1])

In [13]:
# Using list comprehension - create a list - replacing 0 with epsilon
y_predicted_new = [max(epsilon,i) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [14]:
# Using list comprehension - create a list - replacing 1 with 1-epsilon
y_predicted_new = [min(1-epsilon,i) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [15]:
# Convert list to numpy array
y_predicted_new = np.array(y_predicted_new)
y_predicted_new

array([1.e+00, 1.e+00, 1.e-15, 1.e-15, 1.e+00])

In [16]:
# Now applying log will not have a issue
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [17]:
# Create log loss function
-np.mean(y_true * np.log(y_predicted_new) +  (1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [18]:
# Combine all the above steps in one single function
def log_loss(y_predicted, y_true):
  epsilon = 1e-15
  y_predicted_new = [ max(epsilon, i) for i in y_predicted]
  y_predicted_new = [ min(1-epsilon, i) for i in y_predicted_new]
  y_predicted_new = np.array(y_predicted_new)
  return -np.mean(y_true * np.log(y_predicted_new) + (1-y_true) * np.log(1-y_predicted_new))

log_loss(y_predicted, y_true)

17.2696280766844

### Exercise
Implement mean squared error (or MSE) in two ways,

Without using numpy (i.e. using plain python)

With the use of numpy

In [19]:
# Without numpy
def mse(y_predicted, y_true):
  total_error = 0
  for yp, yt in zip(y_predicted, y_true):
    print(yp, yt)
    total_error += (yp-yt)**2
  print(total_error)
  mse = total_error/len(y_true)
  return mse

In [20]:
mse(y_predicted, y_true)

1 0.3
1 0.7
0 1.0
0 0.0
1 0.5
1.83


0.366

In [21]:
# Using numpy
def mse(y_predicted, y_true):
  return np.mean(np.square(y_predicted-y_true))

mse(y_predicted, y_true)

0.366